spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: test1234
  application:
    name: DSDB-Collaborators

server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
