spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/features
    username: test1234
    password: test1234
  application:
    name: DSDB-Features
server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
