spring:
  # Postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=music
    username: test1234
    password: test1234
  # JPA & Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: true
  # Application Name
  application:
    name: DSDB-Features
# Server port
server:
  port: 8083

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
