# Server port
server:
  port: 8082

spring:
  # MongoDB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: music
  main:
    allow-bean-definition-overriding: true

  application:
    name: DSDB-Music
  redis:
    host: localhost
    port: 6379

  cache:
    cache-names: music
    redis:
      time-to-live: 60000
    type: redis

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

