server:
  port: 80

eureka:
  instance:
    prefer-ip-address: true # Registers ip rather than server name
  client:
    register-with-eureka: true # register this app at eureka
    fetch-registry: true # pull down a local copy of the registries
    service-url:
      defaultZone: http://localhost:8761/eureka # discovery service location

spring:
  application:
    name: DSDB-Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #Enables eureka discovery service
      routes:
        - id: DSDB-Users
          uri: lb://dsdb-users
          predicates:
            - Path=/users/**, /login/**
        - id: DSDB-Features
          uri: lb://dsdb-features
          predicates:
            - Path=/features/**
        - id: DSDB-Music
          uri: lb://dsdb-music
          predicates:
            - Path=/music/**
        - id: DSDB-Lyrics
            uri: lb://dsdb-lyrics
            predicates:
              - Path=/lyrics/**
